spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: claims-app
      auto-offset-reset: earliest
    producer:
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
    properties:
      spring.json.trusted.packages: com.example.claims.model,com.example"
      schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}
    streams:
      application-id: claims-streams-app
      auto-startup: true
      properties:
        cache.max.bytes.buffering: 0
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerde
        schema.registry.url: ${SCHEMA_REGISTRY_URL:http://schema-registry:8081}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
  metrics:
    enable:
      all: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        claims.api.post.time: true
        claims.input.processing.time: true
        claims.highvalue.processing.time: true
      percentiles:
        claims.api.post.time: 0.5, 0.95, 0.99
        claims.input.processing.time: 0.5, 0.95, 0.99
        claims.highvalue.processing.time: 0.5, 0.95, 0.99

logging:
  level:
    root: INFO
    com.example.claims: INFO
    org.apache.kafka: INFO
